#!/bin/bash

set -e

dir=$(dirname "$0")

run_tests() {
  dir=$1
  mode=$2
  shift 2

  defaultoptslist=("$@")
  if ((${#defaultoptslist[@]} == 0)); then
    defaultoptslist=('')
  fi

  cd "$dir"
  for file in *.cl; do
    optslist=()
    #IFS=$'\n' for i in "$(sed -ne 's/^--cool:test=(.*)/\1/p')"; do
    while IFS= read -r opts; do
      optslist+=("$opts")
    done < <(sed -ne 's/^--test=//p' "$file")

    if ((${#optslist[@]} == 0)); then
      optslist=("${defaultoptslist[@]}")
    fi

    for opts in "${optslist[@]}"; do
      opts=($opts)
      echo -n "cool" $mode "${opts[@]}" "$dir/$file"

      redir=${file%.cl}.in
      if test -f "$redir"; then
        echo -n " < $redir: "
        actual=$(../../bin/cool $mode "${opts[@]}" "$file" < "$redir")
      else
        echo -n ": "
        actual=$(../../bin/cool $mode "${opts[@]}" "$file")
      fi

      if test "$OSTYPE" = "cygwin"; then
        actual=$(echo "$actual" | tr -d '\r')
      fi
      expected=$(cat "${file%.cl}.txt")

      if test "$actual" != "$expected"; then
        echo "TEST FAILED" >&2
        echo "-- ACTUAL:" >&2
        echo "$actual" | cat -v >&2
        echo "-- EXPECTED:" >&2
        echo "$expected" | cat -v >&2
        exit 1
      else
        echo "TEST PASSED"
      fi
    done
  done
}

(run_tests "$dir"/lex --lex)
(run_tests "$dir"/interpret '' '' '--no-stdin')
