#!/bin/bash

set -e -o pipefail

test=$1

dir=$(dirname "$0")
run_test() {
  file=$1
  shift

  if test -z "$test" -o "$test" = "$file"; then
    echo -n "$file: "
    echo \
      | "$dir"/../bin/interpreter-wrapper \
        --format-errors \
        "$dir"/unittest.cl \
        "$dir"/../lib/* \
        "$dir"/"$file" "$@" \
      | {
        success=false
        while IFS= read -r line; do
          case $line in
	  "TEST PASSED"*) success=true;;
	  "ERROR: "*": Exception: case without matching branch: TestAssertionFailed(...)") continue
	  esac
	  echo "$line"
        done
        $success
      }
  fi
}

run_test util-unittest.cl
run_test linked-list-unittest.cl
run_test string-list-map-unittest.cl
run_test io-unittest.cl
run_test tokenizer-unittest.cl
run_test parser-unittest.cl
run_test analyzer-unittest.cl
