#!/bin/bash

set -e -o pipefail

test=$1

dir=$(dirname "$0")
run_test() {
  name=$1
  shift

  if test -z "$test" -o "$test" = "$name"; then
    echo -n "$name: "
    echo \
      | "$dir"/../bin/interpreter-wrapper \
        --format-errors \
        "$dir"/unittest.cl \
        "$dir"/../lib/* \
        "$dir"/"$name"-unittest.cl "$@" \
      | {
        success=false
        while IFS= read -r line; do
          case $line in
	  "TEST PASSED"*) success=true;;
	  "ERROR: "*": Exception: case without matching branch: TestAssertionFailed(...)") continue
	  esac
	  echo "$line"
        done
        $success
      }
  fi
}

run_test util
run_test linked-list
run_test string-list-map
run_test int-tree-map
run_test io
run_test tokenizer
run_test parser
run_test analyzer
